services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: emoji_game_dev
    ports:
      - "5432:5432"


  graphite_statsd:
    image: graphiteapp/graphite-statsd:1.1.8-1
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"